config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "boards#index"
  resources :boards do
    resources :pins
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :pins, dependent: :destroy
  belongs_to :user
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :board
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :boards
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end
  def show
    @board = Board.find(params[:id])
  end
  def new
    @board = Board.new
  end
  def create
    @board = Board.create(board_params.merge(user:current_user))
    redirect_to @board
  end
  def destroy
    @board = current_user.boards.find(params[:id]).destroy
    redirect_to boards_path
  end
  private
  def board_params
    params.require(:board).permit(:title)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  def new
    @board = Board.find(params[:board_id])
    @pin = @board.pins.new
  end
  def create
    @board = Board.find(params[:board_id])
    @pin = @board.pins.create(pin_params.merge(user: current_user))
    redirect_to board_path( @board )
  end
  def destroy
    @board = Board.find(params[:board_id])
    @pin = current_user.pins.find(params[:id])
    @pin.destroy
    redirect_to board_path(@board)
  end
  private
  def pin_params
    params.require(:pin).permit(:title, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.erb
<%= form_for @board do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/boards/index.html.erb
<h2>All Boards</h2>
<% @boards.each do |board| %>
<div class='board row'>
  <%= link_to board.title, board_path(board) %>
</div>
<% end %>

<% if current_user %>
<h2>My Boards</h2>
  <% current_user.boards.each do |board| %>
    <div class='board row'>
      <%= link_to board.title, board_path(board) %>
    </div>
  <% end %>
<% end %>

app/views/boards/new.html.erb
<h2>Create New Board</h2>

<%= render "form" %>

app/views/boards/show.html.erb
<%= link_to "&larr; Back".html_safe, boards_path %> 
<h2><%= @board.title %></h2>
<% if @board.user == current_user %>
  <%= link_to "Delete Board", board_path(@board), method: :delete%>
  <%= link_to "Create New Pin", new_board_pin_path(@board) %>
  <br><br>
<% end %>
<div class='board masonry'>
  <% @board.pins.each do |pin| %>
    <div class='pin'>
      <h3><%= pin.title %></h3>
      <%= image_tag pin.image_url %>
      <% if current_user && pin.user == current_user %>
	<%= link_to "x", board_pin_path(@board, pin), method: :delete %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinspiration</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class='cf'>
  <h1><%= link_to "Pinspiration", root_path %></h1>
  <nav>
    <% if current_user %>
      <%= link_to "Create New Board", new_board_path %>
      <%= link_to "Log Out #{current_user.email}", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>
  </nav>
</header>

<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for [@board, @pin] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
  <%= f.submit %>
<% end %>

app/views/pins/new.html.erb
<h2>Create New Pin</h2>
<%= render "form" %>